-Successfully implemented logging in and out functionality (happy path) by fully implementing SecurityConfig, LoginController, and SignupController. -The first 3 tests run successfully (testLargeUpload, getLoginPage, testBadUrl) run successfully, although testLargeUpload is a false positive at this point because I haven't implemented storage functionalities yet. -Added guava dependency, this was needed for tests to run to solve java.lang.NoSuchMethodError.
To do:
-implement home controller
-implement result controller
-other rubric items.